# Generated by Django 5.1.5 on 2025-01-18 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='feedback_style',
        ),
    ]
