# Generated by Django 5.1.5 on 2025-01-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_remove_journalentry_feedback_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Journal entries'},
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='content',
            field=models.TextField(help_text='Journal entry content in HTML format'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
