# Generated by Django 4.2.18 on 2025-02-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journalentry_analysis_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='analysis_mode',
            field=models.CharField(choices=[('therapist', 'CBT Therapist'), ('mindfulness', 'Mindfulness Counselor'), ('reflection', 'Reflection Guide'), ('growth', 'Growth Mentor')], default='therapist', help_text='Type of AI analysis to perform', max_length=20),
        ),
    ]
