# Generated by Django 4.2.18 on 2025-02-02 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0005_alter_journalentry_analysis_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, help_text='Personal goals and aspirations')),
                ('openness', models.IntegerField(default=50, help_text='Openness to Experience')),
                ('conscientiousness', models.IntegerField(default=50)),
                ('extraversion', models.IntegerField(default=50)),
                ('agreeableness', models.IntegerField(default=50)),
                ('neuroticism', models.IntegerField(default=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('interests', models.TextField(blank=True)),
                ('values', models.TextField(blank=True, help_text='Personal values and beliefs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
