# Generated by Django 4.2.18 on 2025-02-04 03:59

from django.db import migrations


def add_initial_programs(apps, schema_editor):
    GuidedProgram = apps.get_model('journal', 'GuidedProgram')
    GuidedSession = apps.get_model('journal', 'GuidedSession')

    # Create Expressive Writing Program
    expressive = GuidedProgram.objects.create(
        name='Expressive Writing Journey',
        description='A structured 5-day program based on Dr. James Pennebaker\'s expressive writing paradigm. Write about your deepest thoughts and feelings to improve emotional well-being.',
        total_sessions=5
    )

    # Create sessions for Expressive Writing
    sessions = [
        {
            'program': expressive,
            'session_number': 1,
            'title': 'Getting Started with Expressive Writing',
            'description': 'An introduction to expressive writing and its benefits.',
            'prompt': 'Write about something that has been bothering you lately. Don\'t worry about grammar or spelling - just write continuously for 15-20 minutes about your deepest thoughts and feelings.'
        },
        {
            'program': expressive,
            'session_number': 2,
            'title': 'Exploring Emotions',
            'description': 'Dive deeper into your emotional experiences.',
            'prompt': 'Continue writing about the same topic or choose a new one. How did these events make you feel? What emotions come up when you think about this?'
        },
        {
            'program': expressive,
            'session_number': 3,
            'title': 'Finding Meaning',
            'description': 'Reflect on how experiences have shaped you.',
            'prompt': 'Write about how this experience has affected your life. What have you learned? How has it changed your perspective?'
        },
        {
            'program': expressive,
            'session_number': 4,
            'title': 'Different Perspectives',
            'description': 'Look at your experiences from new angles.',
            'prompt': 'Write about the same experience but try to see it from a different perspective. What might others involved think or feel? What other ways could you interpret what happened?'
        },
        {
            'program': expressive,
            'session_number': 5,
            'title': 'Integration and Moving Forward',
            'description': 'Wrap up your expressive writing journey.',
            'prompt': 'Reflect on your writing journey. How do you feel about these experiences now? What insights have you gained? How might you use these insights moving forward?'
        }
    ]

    for session_data in sessions:
        GuidedSession.objects.create(**session_data)

    # Create Gratitude Journal Program
    gratitude = GuidedProgram.objects.create(
        name='Gratitude Practice',
        description='A 7-day program to cultivate gratitude and appreciation in your daily life. Regular gratitude practice has been shown to increase happiness and well-being.',
        total_sessions=7
    )

    # Create sessions for Gratitude Journal
    gratitude_sessions = [
        {
            'program': gratitude,
            'session_number': 1,
            'title': 'Simple Pleasures',
            'description': 'Start with noticing the small things.',
            'prompt': 'Write about three simple pleasures you experienced today. What made them special?'
        },
        {
            'program': gratitude,
            'session_number': 2,
            'title': 'People in Your Life',
            'description': 'Focus on relationships and connections.',
            'prompt': 'Write about someone who has positively impacted your life. What qualities do you appreciate about them?'
        },
        {
            'program': gratitude,
            'session_number': 3,
            'title': 'Challenges and Growth',
            'description': 'Find gratitude in difficult experiences.',
            'prompt': 'Write about a challenge that led to unexpected growth or learning. What are you grateful for about this experience?'
        },
        {
            'program': gratitude,
            'session_number': 4,
            'title': 'Nature and Beauty',
            'description': 'Appreciate the natural world.',
            'prompt': 'Write about something beautiful in nature that you noticed today. How did it make you feel?'
        },
        {
            'program': gratitude,
            'session_number': 5,
            'title': 'Personal Strengths',
            'description': 'Recognize your own qualities.',
            'prompt': 'Write about three personal qualities or abilities you\'re grateful for. How have they helped you?'
        },
        {
            'program': gratitude,
            'session_number': 6,
            'title': 'Everyday Opportunities',
            'description': 'Notice daily blessings.',
            'prompt': 'Write about three opportunities or privileges you have that you might take for granted.'
        },
        {
            'program': gratitude,
            'session_number': 7,
            'title': 'Looking Forward',
            'description': 'Set intentions for continued practice.',
            'prompt': 'Reflect on how this gratitude practice has affected you. What would you like to continue noticing and appreciating?'
        }
    ]

    for session_data in gratitude_sessions:
        GuidedSession.objects.create(**session_data)

def remove_initial_programs(apps, schema_editor):
    GuidedProgram = apps.get_model('journal', 'GuidedProgram')
    GuidedProgram.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_guidedprogram_guidedsession_guidedentry_and_more'),
    ]

    operations = [
        migrations.RunPython(add_initial_programs, remove_initial_programs),
    ]
