# Generated by Django 4.2.18 on 2025-02-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_add_initial_guided_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activities',
            field=models.TextField(blank=True, help_text='Regular activities and hobbies'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='background',
            field=models.TextField(blank=True, help_text='Historical background and experiences'),
        ),
    ]
